# .streamlit/config.toml
[server]
headless = true
port = 8501
enableCORS = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#4CAF50"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
